import { useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { useGetGallery, useReactToGallery } from "@workspace/api-client-react";
import { formatDistanceToNow } from "date-fns";
import { Play, Pause, AlertCircle, Share2, Check } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Skeleton } from "@/components/ui/skeleton";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import { motion } from "framer-motion";

export default function Gallery() {
  const { data, isLoading, error, refetch } = useGetGallery({ limit: 50, offset: 0 });
  const { toast } = useToast();
  const reactMutation = useReactToGallery();

  if (error) {
    return (
      <div className="container mx-auto px-4 py-12 max-w-4xl">
        <Alert variant="destructive">
          <AlertCircle className="h-4 w-4" />
          <AlertTitle>Error</AlertTitle>
          <AlertDescription>Failed to load gallery entries. Please try again later.</AlertDescription>
        </Alert>
      </div>
    );
  }

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.5 }}
      className="container mx-auto px-4 py-12 max-w-5xl"
    >
      <motion.div
        initial={{ y: -20, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ duration: 0.6 }}
        className="mb-12 text-center space-y-4"
      >
        <h1 className="text-5xl font-display uppercase tracking-widest">
          <motion.span
            className="text-primary inline-block"
            animate={{ textShadow: ["0 0 15px rgba(255,51,51,0.4)", "0 0 30px rgba(255,51,51,0.6)", "0 0 15px rgba(255,51,51,0.4)"] }}
            transition={{ duration: 2, repeat: Infinity }}
          >
            The Hall of
          </motion.span>{" "}
          <span className="text-foreground">Screams</span>
        </h1>
        <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
          Browse the most unhinged, dramatic rants generated by others.
          Listen at your own risk.
        </p>
      </motion.div>

      {isLoading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {[1, 2, 3, 4].map(i => (
            <Card key={i} className="bg-card/50 border-border/50">
              <CardContent className="p-6 space-y-4">
                <Skeleton className="h-4 w-24" />
                <Skeleton className="h-20 w-full" />
                <Skeleton className="h-10 w-full" />
                <div className="flex gap-2">
                  <Skeleton className="h-8 w-16" />
                  <Skeleton className="h-8 w-16" />
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {data?.entries.map((entry, i) => (
            <motion.div
              key={entry.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.1, duration: 0.5 }}
            >
              <GalleryCard
                entry={entry}
                onReact={async (emoji) => {
                  try {
                    await reactMutation.mutateAsync({ id: entry.id, data: { emoji } });
                    refetch();
                  } catch {
                    toast({
                      title: "Failed to react",
                      description: "Something went wrong.",
                      variant: "destructive"
                    });
                  }
                }}
              />
            </motion.div>
          ))}

          {data?.entries.length === 0 && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="col-span-full text-center py-20 text-muted-foreground border border-dashed border-border rounded-xl glass-card"
            >
              No screams have been echoed yet. Be the first!
            </motion.div>
          )}
        </div>
      )}
    </motion.div>
  );
}

function GalleryCard({ entry, onReact }: { entry: any, onReact: (emoji: string) => void }) {
  const [isPlaying, setIsPlaying] = useState(false);
  const [copied, setCopied] = useState(false);
  const [audio] = useState(() => new Audio(entry.audio_url));
  const { toast } = useToast();

  const togglePlay = () => {
    if (isPlaying) {
      audio.pause();
    } else {
      audio.play();
    }
    setIsPlaying(!isPlaying);
  };

  audio.onended = () => setIsPlaying(false);

  const emojis = ["🔥", "💀", "😂"];
  const reactions = entry.reactions || {};

  return (
    <motion.div whileHover={{ y: -3 }} transition={{ type: "spring", stiffness: 300 }}>
      <Card className="glass-card hover:border-primary/20 transition-all duration-300 overflow-hidden flex flex-col group">
        <div className="p-1 bg-gradient-to-r from-primary/50 to-secondary/50 w-full transition-opacity group-hover:opacity-100 opacity-70" />
        <CardContent className="p-6 flex flex-col flex-1 space-y-6">
          <div className="flex items-center justify-between">
            <Badge variant="outline" className="text-xs uppercase tracking-wider text-secondary border-secondary/30 bg-secondary/5">
              {entry.mode.replace('_', ' ')}
            </Badge>
            <span className="text-xs text-muted-foreground">
              {formatDistanceToNow(new Date(entry.created_at), { addSuffix: true })}
            </span>
          </div>

          <div className="space-y-4 flex-1">
            <div className="space-y-1">
              <p className="text-xs font-bold text-muted-foreground uppercase">Original</p>
              <p className="text-sm text-muted-foreground line-clamp-2 italic">"{entry.original_text}"</p>
            </div>

            <div className="space-y-1">
              <p className="text-xs font-bold text-primary uppercase">Dramatic Translation</p>
              <p className="text-lg font-medium leading-tight text-foreground line-clamp-4">
                "{entry.translated_text}"
              </p>
            </div>
          </div>

          <div className="space-y-4 pt-4 border-t border-border/50 mt-auto">
            <div className="flex items-center justify-between">
              <motion.div whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>
                <Button
                  variant="default"
                  size="sm"
                  className={`${isPlaying ? "bg-primary text-white shadow-[0_0_15px_rgba(255,51,51,0.3)]" : "bg-primary/20 text-primary hover:bg-primary hover:text-white"} transition-all`}
                  onClick={togglePlay}
                >
                  {isPlaying ? <Pause className="w-4 h-4 mr-2" /> : <Play className="w-4 h-4 mr-2" />}
                  {isPlaying ? "Playing..." : "Listen"}
                </Button>
              </motion.div>

              <motion.div whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>
                <Button
                  variant="outline"
                  size="sm"
                  className="h-8 px-2 text-xs border-border hover:border-primary/30 transition-all"
                  onClick={() => {
                    const url = `${window.location.origin}${entry.audio_url}`;
                    navigator.clipboard.writeText(url);
                    setCopied(true);
                    toast({ title: "Link copied!", description: "Share this dramatic rant with anyone." });
                    setTimeout(() => setCopied(false), 2000);
                  }}
                >
                  {copied ? <Check className="w-3.5 h-3.5 mr-1 text-green-400" /> : <Share2 className="w-3.5 h-3.5 mr-1" />}
                  {copied ? "Copied" : "Share"}
                </Button>
              </motion.div>
            </div>

            <div className="flex items-center gap-2">
              {emojis.map(emoji => (
                <motion.div key={emoji} whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.9 }}>
                  <Button
                    variant="outline"
                    size="sm"
                    className="h-8 px-2 bg-background/50 text-xs border-border hover:bg-muted hover:border-primary/30 transition-all"
                    onClick={() => onReact(emoji)}
                  >
                    {emoji} {reactions[emoji] || 0}
                  </Button>
                </motion.div>
              ))}
            </div>
          </div>
        </CardContent>
      </Card>
    </motion.div>
  );
}
